apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: shopping-cart
    releaseName: shopping-cart
    namespace: shopping-prod
    valuesFile: values-prod.yaml

patches:
  - path: ingress-patch.yaml
    target:
      kind: Service
      name: shopping-cart