apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base


### This prefixes the metadata.name
namePrefix: dev-
### This injects the specified key-value pair (
commonLabels:
  environment: dev
